### ISSUE TITLE
Two "success" notifications?

### ISSUE THREAD

**Issue by coopr** [rtCamp/rt-newrelic-browser#16]
Not a big deal, but when I first added this plugin to a new WP site, I saw the attached. Note that I've not seen this in my previous testing.

![new_relic_options_ _iona_dreaming_ _wordpress](https://cloud.githubusercontent.com/assets/94904/5766853/5bff9c94-9cb9-11e4-8fd7-e5865c25a79f.jpg)

**Comment by coopr** [comment]
And, I just noticed, I got two "Welcome" emails this time.

**Comment by rohanveer-rtcamp** [comment]
Added more validations to handle form submission.

**Comment by coopr** [comment]
Tested, looks great to me, thanks!
