### ISSUE TITLE
applicationID and licenseKey are set twice

### ISSUE THREAD

**Issue by coopr** [rtCamp/rt-newrelic-browser#17]
In the injected New Relic Browser JS I'm seeing the applicationID and licenseKey set twice - this is causing the script to not execute.

My colleague pointed out "They included the NREUM.info={...} block and then followed it by setting the applicationID and licenseKey separately."

Please review the latest changes to our docs https://gist.github.com/coopr/434707d03bf92adc9e8d/revisions and make the necessary changes to your code, thanks!

**Comment by rohanveer-rtcamp** [comment]
We have updated the script as per your new docs.

**Comment by coopr** [comment]
Tested, looks great to me, thanks!
